### ISSUE TITLE
Failed Open Google Sateliite

### ISSUE THREAD

**Issue by kangozidev** [wp-xyz/lazmapviewer#1]
Thanks for your Map package 

I found a little trouble to access google sateliite
I try fix some code in mvEngine.pas

AddMapProvider('Google Satellite', ptEPSG3857, 'http://khm%serv%.google.com/kh/v=863?x=%x%&y=%y%&z=%z%' , 0, 19, 4, nil);

i change to 

 AddMapProvider('Google Satellite', ptEPSG3857, 'http://mt0.google.com/vt/lyrs=y&hl=en&x=%x%&y=%y%&z=%z%' , 0, 19, 4, nil);

and success load Google Satellite

**Comment by wp-xyz** [comment]
Thank you for reporting and fixing. BTW, do you have a fix also for the OpenStreetMap Sputnik provider where I don't get any response either?

I did apply your patch, however, to the svn version on sourceforge since I will be deleting the gitub test repository soon.

**Comment by kangozidev** [comment]
I'll try

**Comment by kangozidev** [comment]
some googlemap tile service

 AddMapProvider('Google Terrain', ptEPSG3857, 'http://mt0.google.com/vt/lyrs=p&hl=en&x=%x%&y=%y%&z=%z%' , 0, 19, 4, nil);
  AddMapProvider('Google Satellite only', ptEPSG3857, 'http://mt0.google.com/vt/lyrs=s&hl=en&x=%x%&y=%y%&z=%z%' , 0, 19, 4, nil);
  AddMapProvider('Google Altered roadmap', ptEPSG3857, 'http://mt0.google.com/vt/lyrs=r&hl=en&x=%x%&y=%y%&z=%z%' , 0, 19, 4, nil);
  AddMapProvider('Google roadmap', ptEPSG3857, 'http://mt0.google.com/vt/lyrs=m&hl=en&x=%x%&y=%y%&z=%z%' , 0, 19, 4, nil);

**Comment by wp-xyz** [comment]
Thank you. Added to CCR version. Synchronized github version with current CCR version.
